name: Build and Push

on:
  push:
    branches: [ "project/2024wrapped" ]
  pull_request:
    branches: [ "project/2024wrapped" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
       docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    - name: Log in to the Container Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghrc.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to Github Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with: 
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ stesp.push.outputs.digest }}
        push-to-registry: true
